debug: true
app:
  namespace: common-basics
  org-code: security
  data:
    jdbc:
      datasource:
        primary:
          url:
            host: cb.fw.definex.com.tr
            service_name: srv_security
        secondary:
          url:
            host: bck.cb.fw.definex.com.tr
            service_name: srv_security
  online:
    grpc:
      clients:
        - service: market-place
          port: 6565
        - service: cryptography
          port: 6565
        - service: end-to-end-process-monitoring
          port: 6565
server:
  port: 9081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
keycloak-client:
  server-url: http://definexappsrv.westeurope.cloudapp.azure.com:18080/auth
  realm:  definex-apaas-main
spring:
  application:
    name: auth-management-service
    id: auth-management-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: spring-micro-producer
            client-secret: 397114a3-1d5c-4173-a5d4-228c0a5389b1
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9081/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

